# Generated by Django 3.2.2 on 2021-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_rename_user_todo_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('HG', 'High'), ('MD', 'Medium'), ('LW', 'Low')], default='HG', max_length=6),
        ),
    ]
